server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: file:///${user.home}/Desktop/Spring-boot-msa-ex
          default-label: main
